/*
 * verimark-tls.c — see verimark-tls.h. Hand-rolled Synaptics "Tudor" TLS 1.2
 * handshake state machine + record layer. SPDX-License-Identifier: LGPL-2.1-or-later
 *
 * Oracle: re/synaTudor-rev/pydrv/tudor/tls/{session,handshake,record}.py +
 * data/handshake/{hello,cert,kex,finished,extensions}.py + cipher/{ecc,encr}.py.
 * Golden vectors: driver/tests/handshake_vectors.h (generated by
 * driver/tests/gen_handshake_vectors.py, which drives rev's own client).
 *
 * Wire-level notes (all confirmed byte-for-byte against the generated vectors):
 *  - Record header: content_type(1) | 0x03 0x03 | length(2 BE) | fragment.
 *  - Handshake message header: msg_id(1) | length(3 BE) | body.
 *  - Transcript hash is SHA-256 over raw handshake-message bytes (id|len|body),
 *    in send/receive order, EXCLUDING Finished (id 0x14) — handshake.py:67-68,80-81.
 *  - PRF (master secret / key expansion / Finished verify_data) is SHA-384.
 *  - CertificateVerify signs the transcript digest snapshotted AFTER Certificate+
 *    ClientKeyExchange but BEFORE CertificateVerify itself is appended (ecc.py:79-81).
 *  - Both the client's and the server's Finished verify_data use the digest snapshot
 *    taken AFTER CertificateVerify is appended (handshake.py:129,141) — call this dB.
 *  - AEAD content_type in the GCM AAD is a per-record value: 0x16 for the Finished
 *    messages, 0x17 for steady-state application_data, 0x15 for alerts.
 */
#define FP_COMPONENT "verimark"
#define OPENSSL_API_COMPAT 0x10100000L  /* legacy EC_KEY API; silence 3.0 deprecations */
#include "verimark-tls.h"
#include <string.h>
#include <openssl/evp.h>
#include <openssl/rand.h>

struct _VerimarkTls {
  VerimarkTlsIo io;
  gpointer      io_ctx;

  gboolean have_pairing;
  gboolean established;
  VerimarkPairing pd;

  guint8  client_random[32];
  guint8  server_random[32];
  guint8  eph_priv[32];
  guint8  master_secret[48];
  guint8  verify_digest[32];      /* dB: transcript digest after CertVerify appended */
  VerimarkTlsKeys keys;

  guint64 encr_seq, decr_seq;

  EVP_MD_CTX *transcript;         /* SHA-256, excludes Finished */

#ifdef VERIMARK_TESTING
  gboolean pin_client_random_set, pin_eph_priv_set, pin_gcm_nonce_set;
  guint8   pin_client_random[32], pin_eph_priv[32], pin_gcm_nonce[8];
  gboolean pin_cert_verify_sig_set;
  guint8   pin_cert_verify_sig[80];
  gsize    pin_cert_verify_sig_len;
#endif
};

/* -------------------------------------------------------------------------
 * Record + transcript helpers
 * ---------------------------------------------------------------------- */

/* Plaintext record: content_type ‖ 0x03 0x03 ‖ len(2 BE) ‖ body. */
static void
rec_write_plain (GByteArray *out, guint8 ct, const guint8 *body, gsize n)
{
  guint8 hdr[5] = { ct, 0x03, 0x03, (guint8) (n >> 8), (guint8) (n & 0xff) };
  g_byte_array_append (out, hdr, 5);
  if (n) g_byte_array_append (out, body, n);
}

/* Handshake message: id ‖ len(3 BE) ‖ body; also feeds the raw bytes into the
 * transcript unless id is Finished (0x14) — handshake.py:67-68. */
static void
hs_msg (VerimarkTls *t, GByteArray *dst, guint8 id, const guint8 *body, gsize n)
{
  guint8 h[4] = { id, (guint8) (n >> 16), (guint8) (n >> 8), (guint8) (n & 0xff) };
  gsize start = dst->len;
  g_byte_array_append (dst, h, 4);
  if (n) g_byte_array_append (dst, body, n);
  if (id != 0x14)
    EVP_DigestUpdate (t->transcript, dst->data + start, 4 + n);
}

static void
transcript_snapshot (VerimarkTls *t, guint8 digest[32])
{
  EVP_MD_CTX *copy = EVP_MD_CTX_new ();
  EVP_MD_CTX_copy_ex (copy, t->transcript);
  EVP_DigestFinal_ex (copy, digest, NULL);
  EVP_MD_CTX_free (copy);
}

static void
set_error (GError **error, const char *msg)
{
  g_set_error_literal (error, VERIMARK_TLS_CRYPTO_ERROR, VERIMARK_TLS_CRYPTO_ERROR_FAILED, msg);
}

/* -------------------------------------------------------------------------
 * Construction
 * ---------------------------------------------------------------------- */

VerimarkTls *
verimark_tls_new (VerimarkTlsIo io, gpointer io_ctx)
{
  VerimarkTls *t = g_new0 (VerimarkTls, 1);
  t->io = io;
  t->io_ctx = io_ctx;
  t->transcript = EVP_MD_CTX_new ();
  EVP_DigestInit_ex (t->transcript, EVP_sha256 (), NULL);
  return t;
}

void
verimark_tls_free (VerimarkTls *t)
{
  if (!t) return;
  EVP_MD_CTX_free (t->transcript);
  g_free (t);
}

void
verimark_tls_set_pairing (VerimarkTls *t, const VerimarkPairing *pd)
{
  t->pd = *pd;
  t->have_pairing = TRUE;
}

gboolean
verimark_tls_is_established (VerimarkTls *t)
{
  return t && t->established;
}

#ifdef VERIMARK_TESTING
void
verimark_tls__test_pin (VerimarkTls *t,
                        const guint8 *client_random,
                        const guint8 *eph_priv,
                        const guint8 *gcm_nonce)
{
  if (client_random) { memcpy (t->pin_client_random, client_random, 32); t->pin_client_random_set = TRUE; }
  if (eph_priv)       { memcpy (t->pin_eph_priv, eph_priv, 32);          t->pin_eph_priv_set = TRUE; }
  if (gcm_nonce)       { memcpy (t->pin_gcm_nonce, gcm_nonce, 8);        t->pin_gcm_nonce_set = TRUE; }
}

void
verimark_tls__test_pin_cert_verify_sig (VerimarkTls *t, const guint8 *sig_der, gsize sig_len)
{
  if (sig_der && sig_len && sig_len <= sizeof t->pin_cert_verify_sig)
    {
      memcpy (t->pin_cert_verify_sig, sig_der, sig_len);
      t->pin_cert_verify_sig_len = sig_len;
      t->pin_cert_verify_sig_set = TRUE;
    }
  else
    {
      t->pin_cert_verify_sig_set = FALSE;
    }
}
#endif

/* -------------------------------------------------------------------------
 * Task 2: ClientHello (RT1 request)
 * ---------------------------------------------------------------------- */

/* SupportedGroups(id=10, curves=[23]) and ECPointFormats(id=11, formats=[0]) —
 * extracted from the generated golden_client_hello[] (data/handshake/extensions.py
 * TlsHandshakeExtension framing: ext_id(2) | ext_len(2) | ext_body). */
static const guint8 ext_supported_groups[8]  = { 0x00, 0x0a, 0x00, 0x04, 0x00, 0x02, 0x00, 0x17 };
static const guint8 ext_ec_point_formats[6]  = { 0x00, 0x0b, 0x00, 0x02, 0x01, 0x00 };

static void
hs_build_client_hello (VerimarkTls *t, GByteArray *out)
{
  guint8 cr[32];
#ifdef VERIMARK_TESTING
  if (t->pin_client_random_set)
    memcpy (cr, t->pin_client_random, 32);
  else
#endif
    {
      guint32 now = (guint32) time (NULL);
      cr[0] = (guint8) (now >> 24); cr[1] = (guint8) (now >> 16);
      cr[2] = (guint8) (now >> 8);  cr[3] = (guint8) now;
      RAND_bytes (cr + 4, 28);
    }
  memcpy (t->client_random, cr, 32);

  GByteArray *body = g_byte_array_new ();
  guint8 ver[2] = { 0x03, 0x03 };
  g_byte_array_append (body, ver, 2);
  g_byte_array_append (body, cr, 32);
  guint8 sesid[8] = { 0x07, 0, 0, 0, 0, 0, 0, 0 };
  g_byte_array_append (body, sesid, 8);
  guint8 suites[6] = { 0x00, 0x04, 0xc0, 0x05, 0xc0, 0x2e };
  g_byte_array_append (body, suites, 6);
  guint8 compr[1] = { 0x00 };   /* #BROKEN: no compression method advertised */
  g_byte_array_append (body, compr, 1);
  g_byte_array_append (body, ext_supported_groups, sizeof ext_supported_groups);
  g_byte_array_append (body, ext_ec_point_formats, sizeof ext_ec_point_formats);

  GByteArray *content = g_byte_array_new ();
  hs_msg (t, content, 0x01, body->data, body->len);
  rec_write_plain (out, 0x16, content->data, content->len);

  g_byte_array_free (body, TRUE);
  g_byte_array_free (content, TRUE);
}

/* -------------------------------------------------------------------------
 * Task 3: parse RT1 response (ServerHello ‖ Certificate ‖ CertificateRequest ‖
 * ServerHelloDone)
 * ---------------------------------------------------------------------- */

static gboolean
hs_process_rt1 (VerimarkTls *t, const guint8 *resp, gsize resp_len, GError **error)
{
  /* Split into records, concatenating ct==0x16 fragments (RT1 is all plaintext
   * handshake). */
  GByteArray *hsbuf = g_byte_array_new ();
  gsize off = 0;
  while (off < resp_len)
    {
      if (off + 5 > resp_len) { set_error (error, "RT1: truncated record header"); g_byte_array_free (hsbuf, TRUE); return FALSE; }
      guint8 ct = resp[off];
      guint16 rlen = (guint16) ((resp[off + 3] << 8) | resp[off + 4]);
      if (off + 5 + rlen > resp_len) { set_error (error, "RT1: truncated record body"); g_byte_array_free (hsbuf, TRUE); return FALSE; }
      if (ct != 0x16) { set_error (error, "RT1: unexpected content type"); g_byte_array_free (hsbuf, TRUE); return FALSE; }
      g_byte_array_append (hsbuf, resp + off + 5, rlen);
      off += 5 + rlen;
    }

  gboolean got_server_hello = FALSE, rt1_done = FALSE;
  off = 0;
  while (off < hsbuf->len)
    {
      if (off + 4 > hsbuf->len) { set_error (error, "RT1: truncated handshake header"); g_byte_array_free (hsbuf, TRUE); return FALSE; }
      guint8 id = hsbuf->data[off];
      gsize mlen = ((gsize) hsbuf->data[off + 1] << 16) | ((gsize) hsbuf->data[off + 2] << 8) | hsbuf->data[off + 3];
      if (off + 4 + mlen > hsbuf->len) { set_error (error, "RT1: truncated handshake body"); g_byte_array_free (hsbuf, TRUE); return FALSE; }
      const guint8 *body = hsbuf->data + off + 4;

      EVP_DigestUpdate (t->transcript, hsbuf->data + off, 4 + mlen);   /* id != 0x14 always here */

      if (rt1_done) { set_error (error, "RT1: message after ServerHelloDone"); g_byte_array_free (hsbuf, TRUE); return FALSE; }

      switch (id)
        {
        case 0x02: /* ServerHello */
          if (mlen < 2 + 32 + 1 + 2 + 1) { set_error (error, "RT1: ServerHello too short"); g_byte_array_free (hsbuf, TRUE); return FALSE; }
          /* Do NOT validate the ServerHello protocol version: this sensor
           * returns a non-0x0303 value (observed 0x0383) and rev never checks
           * it (TlsProtocolVersion.read in tls/data/record.py:20-22 just reads
           * the two bytes; the version is never used in key derivation). The
           * two version bytes are still fed to the transcript hash above via
           * EVP_DigestUpdate over the whole message. */
          memcpy (t->server_random, body + 2, 32);
          {
            guint8 ses_len = body[34];
            gsize p = 35 + ses_len;
            if (p + 3 > mlen) { set_error (error, "RT1: ServerHello session id overruns"); g_byte_array_free (hsbuf, TRUE); return FALSE; }
            guint16 suite = (guint16) ((body[p] << 8) | body[p + 1]);
            if (suite != 0xc02e) { set_error (error, "RT1: unexpected cipher suite (want 0xC02E)"); g_byte_array_free (hsbuf, TRUE); return FALSE; }
          }
          got_server_hello = TRUE;
          break;
        case 0x0b: /* Certificate — transcript only, contents ignored (ecc.py:50-54) */
          break;
        case 0x0d: /* CertificateRequest */
          if (mlen < 1) { set_error (error, "RT1: CertificateRequest too short"); g_byte_array_free (hsbuf, TRUE); return FALSE; }
          {
            guint8 count = body[0];
            if ((gsize) 1 + count > mlen) { set_error (error, "RT1: CertificateRequest cert-type vector overruns"); g_byte_array_free (hsbuf, TRUE); return FALSE; }
            gboolean has_ecdsa = FALSE;
            for (guint8 i = 0; i < count; i++)
              if (body[1 + i] == 64) has_ecdsa = TRUE;   /* ECDSA_SIGN */
            if (!has_ecdsa) { set_error (error, "RT1: CertificateRequest lacks ECDSA_SIGN"); g_byte_array_free (hsbuf, TRUE); return FALSE; }
          }
          break;
        case 0x0e: /* ServerHelloDone */
          if (!got_server_hello) { set_error (error, "RT1: ServerHelloDone before ServerHello"); g_byte_array_free (hsbuf, TRUE); return FALSE; }
          rt1_done = TRUE;
          break;
        default:
          set_error (error, "RT1: unexpected handshake message id");
          g_byte_array_free (hsbuf, TRUE);
          return FALSE;
        }

      off += 4 + mlen;
    }

  g_byte_array_free (hsbuf, TRUE);
  if (!rt1_done) { set_error (error, "RT1: incomplete (no ServerHelloDone)"); return FALSE; }
  return TRUE;
}

/* -------------------------------------------------------------------------
 * Task 4: build RT2 request (Certificate ‖ ClientKeyExchange ‖ CertificateVerify
 * ‖ ChangeCipherSpec ‖ Finished)
 * ---------------------------------------------------------------------- */

static gboolean
hs_build_rt2 (VerimarkTls *t, GByteArray *out, GError **error)
{
  GByteArray *content16 = g_byte_array_new ();

  /* --- Certificate: outer_len(3)=400 ‖ inner_len(3)=400 ‖ garbage(2)=0000 ‖
   * host_cert(400) — cert.py:28-30 (TlsHandshakeCertificate) wrapping
   * crypto.py:56-59 (TlsCertificate, #BROKEN double length prefix). */
  guint8 hostcert400[400];
  if (!verimark_cert_serialize (&t->pd.host_cert, hostcert400, error))
    { g_byte_array_free (content16, TRUE); return FALSE; }
  GByteArray *certbody = g_byte_array_new ();
  guint8 len400[3] = { 0x00, 0x01, 0x90 };   /* 400 BE */
  guint8 garbage[2] = { 0x00, 0x00 };
  g_byte_array_append (certbody, len400, 3);   /* outer_len */
  g_byte_array_append (certbody, len400, 3);   /* inner_len */
  g_byte_array_append (certbody, garbage, 2);
  g_byte_array_append (certbody, hostcert400, 400);
  hs_msg (t, content16, 0x0b, certbody->data, certbody->len);
  g_byte_array_free (certbody, TRUE);

  /* --- ClientKeyExchange: raw EC point, no length prefix (kex.py:18, ecc.py:25-28) */
  guint8 eph_priv[32];
#ifdef VERIMARK_TESTING
  if (t->pin_eph_priv_set)
    memcpy (eph_priv, t->pin_eph_priv, 32);
  else
#endif
    RAND_bytes (eph_priv, 32);
  memcpy (t->eph_priv, eph_priv, 32);

  guint8 eph_pub_x[32], eph_pub_y[32];
  if (!verimark_pub_from_priv (eph_priv, eph_pub_x, eph_pub_y, error))
    { g_byte_array_free (content16, TRUE); return FALSE; }
  guint8 ckebody[65];
  ckebody[0] = 0x04;
  memcpy (ckebody + 1, eph_pub_x, 32);
  memcpy (ckebody + 33, eph_pub_y, 32);
  hs_msg (t, content16, 0x10, ckebody, sizeof ckebody);

  /* --- CertificateVerify: sign the transcript digest as it stands after
   * Certificate+CKE, BEFORE CertVerify itself is appended (ecc.py:79-81). */
  guint8 dA[32];
  transcript_snapshot (t, dA);
  guint8 *sig_der = NULL; gsize sig_len = 0;
#ifdef VERIMARK_TESTING
  if (t->pin_cert_verify_sig_set)
    {
      sig_der = g_memdup2 (t->pin_cert_verify_sig, t->pin_cert_verify_sig_len);
      sig_len = t->pin_cert_verify_sig_len;
    }
  else
#endif
    {
      if (!verimark_ecdsa_sign_prehashed (t->pd.priv_scalar, dA, &sig_der, &sig_len, error))
        { g_byte_array_free (content16, TRUE); return FALSE; }
    }
  hs_msg (t, content16, 0x0f, sig_der, sig_len);   /* raw signature, no length prefix (cert.py:67) */
  g_free (sig_der);

  rec_write_plain (out, 0x16, content16->data, content16->len);
  g_byte_array_free (content16, TRUE);

  /* --- premaster (static ECDH vs the pdata sensor cert, NOT ECDHE) / master
   * secret / key block (ecc.py:84). */
  guint8 premaster[32];
  if (!verimark_ecdh_premaster (eph_priv, t->pd.sensor_cert.pub_x, t->pd.sensor_cert.pub_y, premaster, error))
    return FALSE;
  if (!verimark_tls_derive_master_secret (premaster, sizeof premaster, t->client_random, t->server_random, t->master_secret))
    { set_error (error, "master secret derivation failed"); return FALSE; }
  if (!verimark_tls_derive_keys (t->master_secret, t->client_random, t->server_random, &t->keys))
    { set_error (error, "key block derivation failed"); return FALSE; }
  t->encr_seq = 0;
  t->decr_seq = 0;

  /* --- ChangeCipherSpec: own plaintext record, still under Null encryption
   * (record.py::change_cipher_spec flushes before switching cipher). */
  guint8 ccs_body[1] = { 0x01 };
  rec_write_plain (out, 0x14, ccs_body, 1);

  /* --- snapshot dB (digest after CertVerify appended); both Finisheds use it. */
  transcript_snapshot (t, t->verify_digest);

  guint8 verify_data[12];
  if (!verimark_tls_prf (EVP_sha384 (), t->master_secret, sizeof t->master_secret,
                         "client finished", t->verify_digest, sizeof t->verify_digest,
                         verify_data, sizeof verify_data))
    { set_error (error, "client Finished PRF failed"); return FALSE; }

  GByteArray *finmsg = g_byte_array_new ();
  hs_msg (t, finmsg, 0x14, verify_data, sizeof verify_data);   /* excluded from transcript */

  guint8 nonce[8];
#ifdef VERIMARK_TESTING
  if (t->pin_gcm_nonce_set)
    memcpy (nonce, t->pin_gcm_nonce, 8);
  else
#endif
    RAND_bytes (nonce, 8);

  guint8 *frag = NULL; gsize frag_len = 0;
  /* content_type=0x16 (handshake) in the AAD, NOT 0x17 app-data. */
  if (!verimark_tls_gcm_wrap (t->keys.encr_key, t->keys.encr_iv, t->encr_seq, 0x16, nonce,
                              finmsg->data, finmsg->len, &frag, &frag_len, error))
    { g_byte_array_free (finmsg, TRUE); return FALSE; }
  t->encr_seq++;
  rec_write_plain (out, 0x16, frag, frag_len);
  g_free (frag);
  g_byte_array_free (finmsg, TRUE);

  return TRUE;
}

/* -------------------------------------------------------------------------
 * Task 5: parse RT2 response (ChangeCipherSpec ‖ encrypted server Finished)
 * ---------------------------------------------------------------------- */

static gboolean
hs_process_rt2 (VerimarkTls *t, const guint8 *resp, gsize resp_len, GError **error)
{
  gboolean ccs_seen = FALSE, fin_seen = FALSE;
  gsize off = 0;
  while (off < resp_len)
    {
      if (off + 5 > resp_len) { set_error (error, "RT2: truncated record header"); return FALSE; }
      guint8 ct = resp[off];
      guint16 rlen = (guint16) ((resp[off + 3] << 8) | resp[off + 4]);
      if (off + 5 + rlen > resp_len) { set_error (error, "RT2: truncated record body"); return FALSE; }
      const guint8 *frag = resp + off + 5;

      if (ct == 0x14)
        {
          if (rlen != 1 || frag[0] != 0x01) { set_error (error, "RT2: malformed ChangeCipherSpec"); return FALSE; }
          ccs_seen = TRUE;
        }
      else if (ct == 0x16)
        {
          if (!ccs_seen) { set_error (error, "RT2: Finished before ChangeCipherSpec"); return FALSE; }
          guint8 *plain = NULL; gsize plain_len = 0;
          if (!verimark_tls_gcm_unwrap (t->keys.decr_key, t->keys.decr_iv, t->decr_seq, 0x16,
                                        frag, rlen, &plain, &plain_len, error))
            return FALSE;
          t->decr_seq++;
          if (plain_len != 16 || plain[0] != 0x14) { g_free (plain); set_error (error, "RT2: malformed server Finished"); return FALSE; }

          guint8 expected[12];
          gboolean prf_ok = verimark_tls_prf (EVP_sha384 (), t->master_secret, sizeof t->master_secret,
                                              "server finished", t->verify_digest, sizeof t->verify_digest,
                                              expected, sizeof expected);
          gboolean match = prf_ok && memcmp (plain + 4, expected, 12) == 0;
          g_free (plain);
          if (!match) { set_error (error, "RT2: server Finished verify_data mismatch"); return FALSE; }
          fin_seen = TRUE;
        }
      else
        {
          set_error (error, "RT2: unexpected content type");
          return FALSE;
        }

      off += 5 + rlen;
    }

  if (!ccs_seen || !fin_seen) { set_error (error, "RT2: incomplete"); return FALSE; }
  t->established = TRUE;
  return TRUE;
}

/* -------------------------------------------------------------------------
 * Public: handshake
 * ---------------------------------------------------------------------- */

gboolean
verimark_tls_handshake (VerimarkTls *t, GError **error)
{
  g_return_val_if_fail (t != NULL, FALSE);
  if (!t->have_pairing) { set_error (error, "no pairing set"); return FALSE; }

  GByteArray *out = g_byte_array_new ();
  hs_build_client_hello (t, out);   /* RT1 request */

  guint8 *in = NULL; gsize in_len = 0;
  if (!t->io (t->io_ctx, out->data, out->len, &in, &in_len, error))
    { g_byte_array_free (out, TRUE); return FALSE; }
  if (!hs_process_rt1 (t, in, in_len, error))
    { g_free (in); g_byte_array_free (out, TRUE); return FALSE; }
  g_free (in); in = NULL; in_len = 0;
  g_byte_array_set_size (out, 0);

  if (!hs_build_rt2 (t, out, error))   /* RT2 request */
    { g_byte_array_free (out, TRUE); return FALSE; }
  if (!t->io (t->io_ctx, out->data, out->len, &in, &in_len, error))
    { g_byte_array_free (out, TRUE); return FALSE; }
  g_byte_array_free (out, TRUE);

  if (!hs_process_rt2 (t, in, in_len, error))
    { g_free (in); return FALSE; }
  g_free (in);

  return t->established;
}

/* -------------------------------------------------------------------------
 * Task 6: steady-state wrap / unwrap / close
 * ---------------------------------------------------------------------- */

gboolean
verimark_tls_wrap (VerimarkTls *t,
                   const guint8 *plain, gsize plain_len,
                   guint8 **record, gsize *record_len, GError **error)
{
  g_return_val_if_fail (t != NULL, FALSE);

  if (!t->established)
    {
      *record = plain_len ? g_memdup2 (plain, plain_len) : g_malloc (0);
      *record_len = plain_len;
      return TRUE;
    }

  guint8 nonce[8];
  RAND_bytes (nonce, 8);
  guint8 *frag = NULL; gsize frag_len = 0;
  if (!verimark_tls_gcm_wrap (t->keys.encr_key, t->keys.encr_iv, t->encr_seq,
                              VERIMARK_TLS_CT_APPDATA, nonce, plain, plain_len,
                              &frag, &frag_len, error))
    return FALSE;
  t->encr_seq++;

  GByteArray *out = g_byte_array_new ();
  rec_write_plain (out, VERIMARK_TLS_CT_APPDATA, frag, frag_len);
  g_free (frag);

  *record_len = out->len;
  *record = g_byte_array_free (out, FALSE);
  return TRUE;
}

gboolean
verimark_tls_unwrap (VerimarkTls *t,
                     const guint8 *record, gsize record_len,
                     guint8 **plain, gsize *plain_len, GError **error)
{
  g_return_val_if_fail (t != NULL, FALSE);

  if (!t->established)
    {
      *plain = record_len ? g_memdup2 (record, record_len) : g_malloc (0);
      *plain_len = record_len;
      return TRUE;
    }

  GByteArray *out = g_byte_array_new ();
  gsize off = 0;
  while (off < record_len)
    {
      if (off + 5 > record_len) { set_error (error, "unwrap: truncated record header"); g_byte_array_free (out, TRUE); return FALSE; }
      guint8 ct = record[off];
      guint16 rlen = (guint16) ((record[off + 3] << 8) | record[off + 4]);
      if (off + 5 + rlen > record_len) { set_error (error, "unwrap: truncated record body"); g_byte_array_free (out, TRUE); return FALSE; }
      const guint8 *frag = record + off + 5;

      guint8 *dec = NULL; gsize dec_len = 0;
      if (!verimark_tls_gcm_unwrap (t->keys.decr_key, t->keys.decr_iv, t->decr_seq, ct,
                                    frag, rlen, &dec, &dec_len, error))
        { g_byte_array_free (out, TRUE); return FALSE; }
      t->decr_seq++;

      if (ct == VERIMARK_TLS_CT_APPDATA)
        {
          g_byte_array_append (out, dec, dec_len);
        }
      else if (ct == 0x15)   /* alert */
        {
          g_set_error (error, VERIMARK_TLS_CRYPTO_ERROR, VERIMARK_TLS_CRYPTO_ERROR_FAILED,
                       "TLS alert received (level=%u descr=%u)",
                       dec_len > 0 ? dec[0] : 0, dec_len > 1 ? dec[1] : 0);
          g_free (dec); g_byte_array_free (out, TRUE);
          return FALSE;
        }
      else
        {
          set_error (error, "unwrap: unexpected content type");
          g_free (dec); g_byte_array_free (out, TRUE);
          return FALSE;
        }
      g_free (dec);
      off += 5 + rlen;
    }

  *plain_len = out->len;
  *plain = g_byte_array_free (out, FALSE);
  return TRUE;
}

void
verimark_tls_close (VerimarkTls *t)
{
  if (!t || !t->established) return;

  guint8 body[2] = { 0x01, 0x00 };   /* level=WARNING, descr=CLOSE_NOTIFY */
  guint8 nonce[8];
  RAND_bytes (nonce, 8);

  guint8 *frag = NULL; gsize frag_len = 0;
  GError *err = NULL;
  if (verimark_tls_gcm_wrap (t->keys.encr_key, t->keys.encr_iv, t->encr_seq, 0x15, nonce,
                             body, sizeof body, &frag, &frag_len, &err))
    {
      t->encr_seq++;
      GByteArray *out = g_byte_array_new ();
      rec_write_plain (out, 0x15, frag, frag_len);
      g_free (frag);

      guint8 *in = NULL; gsize in_len = 0; GError *ioerr = NULL;
      t->io (t->io_ctx, out->data, out->len, &in, &in_len, &ioerr);
      g_clear_error (&ioerr);
      g_free (in);
      g_byte_array_free (out, TRUE);
    }
  g_clear_error (&err);

  t->established = FALSE;
}

/* -------------------------------------------------------------------------
 * Test-only seams (see verimark-tls.h)
 * ---------------------------------------------------------------------- */
#ifdef VERIMARK_TESTING
void
verimark_tls__test_build_client_hello (VerimarkTls *t, guint8 **out, gsize *out_len)
{
  GByteArray *b = g_byte_array_new ();
  hs_build_client_hello (t, b);
  *out_len = b->len;
  *out = g_byte_array_free (b, FALSE);
}

gboolean
verimark_tls__test_process_rt1 (VerimarkTls *t, const guint8 *resp, gsize resp_len,
                                guint8 server_random_out[32], GError **error)
{
  if (!hs_process_rt1 (t, resp, resp_len, error)) return FALSE;
  memcpy (server_random_out, t->server_random, 32);
  return TRUE;
}

gboolean
verimark_tls__test_build_rt2 (VerimarkTls *t, guint8 **out, gsize *out_len,
                              guint8 master_secret_out[48], GError **error)
{
  GByteArray *b = g_byte_array_new ();
  if (!hs_build_rt2 (t, b, error)) { g_byte_array_free (b, TRUE); return FALSE; }
  memcpy (master_secret_out, t->master_secret, 48);
  *out_len = b->len;
  *out = g_byte_array_free (b, FALSE);
  return TRUE;
}
#endif
