#!/usr/bin/env python3
# Golden-vector generator for the VeriMark TLS crypto core.
# Run under the repo venv:  PYTHONPATH=re/synaTudor-rev/pydrv ./.venv/bin/python driver/tests/gen_vectors.py
# Emits driver/tests/vectors.h. rev's tudor.tls is the differential oracle.
import os, sys, importlib

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(REPO, "re", "synaTudor-rev", "pydrv"))

from tudor.tls.data.crypto import tls_prf, TlsRandom
from tudor.tls.data.record import TlsCompressed, TlsContentType, TlsProtocolVersion
from tudor.sensor.pair import SensorCertificate, SensorPairingData
import cryptography.hazmat.primitives.ciphers as cipher
import cryptography.hazmat.primitives.hashes as hashes
import cryptography.hazmat.primitives.asymmetric.ec as ecc
encr = importlib.import_module("tudor.tls.cipher.encr")  # importlib avoids a relative-import shadow

OUT = []
def emit_bytes(name, b):
    body = ", ".join("0x%02x" % x for x in b)
    OUT.append("static const guint8 %s[%d] = { %s };" % (name, len(b), body))
def emit_str(name, s):
    OUT.append('static const char %s[] = "%s";' % (name, s))
def emit_define(name, val):
    OUT.append("#define %s %d" % (name, val))
def be32(i):  # big-endian 32-byte encoding of an int
    return i.to_bytes(32, "big")

# ---- PRF (crypto.py::tls_prf) ----
prf_secret = bytes(range(48))
prf_seed   = bytes(range(64))
emit_bytes("prf_sha256_secret", prf_secret); emit_str("prf_sha256_label", "test label")
emit_bytes("prf_sha256_seed", prf_seed)
emit_bytes("prf_sha256_out", tls_prf(prf_secret, "test label", prf_seed, 40, hashes.SHA256()))
emit_bytes("prf_sha384_secret", prf_secret); emit_str("prf_sha384_label", "test label")
emit_bytes("prf_sha384_seed", prf_seed)
emit_bytes("prf_sha384_out", tls_prf(prf_secret, "test label", prf_seed, 40, hashes.SHA384()))

# ---- master secret + key block (cipher/encr.py::TlsAEADEncryptionAlgorithm) ----
premaster = bytes(range(32))
cr_raw = bytes(range(32)); sr_raw = bytes(range(32, 64))
cr = TlsRandom(int.from_bytes(cr_raw[0:4], "big"), cr_raw[4:32])   # .write() == cr_raw
sr = TlsRandom(int.from_bytes(sr_raw[0:4], "big"), sr_raw[4:32])   # .write() == sr_raw
algo = encr.TlsAEADEncryptionAlgorithm(premaster, cr, sr,
        cipher.algorithms.AES, cipher.modes.GCM, hashes.SHA384, 32, 4, 16)
emit_bytes("deriv_premaster", premaster)
emit_bytes("deriv_client_random", cr_raw); emit_bytes("deriv_server_random", sr_raw)
emit_bytes("deriv_master_secret", algo.master_secret)
emit_bytes("deriv_encr_key", algo.encr_key); emit_bytes("deriv_decr_key", algo.decr_key)
emit_bytes("deriv_encr_iv", algo.encr_iv);   emit_bytes("deriv_decr_iv", algo.decr_iv)

# ---- AES-256-GCM record wrap (force a FIXED nonce so the vector is reproducible) ----
FIXED_NONCE = bytes([0xAB] * 8)
encr.secrets.token_bytes = lambda n: FIXED_NONCE[:n]     # seam: rev uses secrets.token_bytes(8)
plain = b"hello verimark!!"
ct = algo.encrypt(TlsCompressed(TlsContentType.types[23], TlsProtocolVersion.current, plain))
emit_bytes("gcm_key", algo.encr_key); emit_bytes("gcm_fixed_iv", algo.encr_iv)
emit_bytes("gcm_nonce", FIXED_NONCE); emit_define("GCM_SEQ", 0)
emit_bytes("gcm_plain", plain); emit_define("gcm_plain_len", len(plain))
emit_bytes("gcm_fragment", ct.fragment); emit_define("gcm_fragment_len", len(ct.fragment))

# ---- SensorCertificate (sensor/pair.py) from a real pdata (sensor cert is public) ----
with open(os.path.join(REPO, "prototype", "pdata", "f7007ad929c60000.pdata"), "rb") as f:
    import io
    pd = SensorPairingData.load(io.BytesIO(f.read()))
sc = pd.sensor_cert
emit_bytes("sensor_cert_400", sc.tobytes())
emit_bytes("sensor_cert_pub_x", be32(sc.pub_key.public_numbers().x))
emit_bytes("sensor_cert_pub_y", be32(sc.pub_key.public_numbers().y))
emit_define("SENSOR_CERT_TYPE", sc.cert_type)
emit_define("SENSOR_CERT_SIGN_SIZE", len(sc.signature))

# ---- .tsk sensor public key (public) + ECDH premaster against sensor cert pubkey ----
with open(os.path.join(REPO, "re", "synaTudor-rev", "pydrv", "tudor", "sensor",
                       "sensor_keys", "10.1-kf.tsk"), "rb") as f:
    tsk = f.read()
tsk_x = int.from_bytes(tsk[0x00:0x44], "little"); tsk_y = int.from_bytes(tsk[0x44:0x88], "little")
emit_bytes("tsk_256", tsk); emit_bytes("tsk_pub_x", be32(tsk_x)); emit_bytes("tsk_pub_y", be32(tsk_y))
eph_priv_int = int.from_bytes(bytes(range(1, 33)), "big")
eph = ecc.derive_private_key(eph_priv_int, ecc.SECP256R1())
premaster_ecdh = eph.exchange(ecc.ECDH(), sc.pub_key)      # exactly ecc.py::end_handshake line 84
emit_bytes("ecdh_eph_priv", be32(eph_priv_int)); emit_bytes("ecdh_premaster", premaster_ecdh)

hdr = "/* GENERATED by driver/tests/gen_vectors.py — do not edit. */\n#pragma once\n#include <glib.h>\n\n"
with open(os.path.join(HERE, "vectors.h"), "w") as f:
    f.write(hdr + "\n".join(OUT) + "\n")
print("wrote", os.path.join(HERE, "vectors.h"), "with", len(OUT), "symbols")
